spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: jArV7UZB2SW5!FhB
  jpa:
    show-sql: true
websiteUrl: http://localhost:8080